import turtle
#Ricardo como nombre 
tortuman=turtle.Turtle()
a=turtle.Screen()
tortuman.speed(6)
tortuman.shapesize(3,3,3)
tortuman.fillcolor("blue")
tortuman.pencolor("green")    
tortuman.pensize(7)
#Letra R
tortuman.lt(90)
tortuman.fd(130)
tortuman.bk(90)
tortuman.right(90)
tortuman.circle(50, 180)
tortuman.left(90)
tortuman.fd(100)
tortuman.left(45)
tortuman.fd(50)
tortuman.penup()
tortuman.left(90)
tortuman.forward(160)
tortuman.left(45)
tortuman.forward(10)
tortuman.left(90)
tortuman.forward(30)
tortuman.pendown()
#letra I
tortuman.forward(40)
tortuman.backward(20)
tortuman.left(90)
tortuman.forward(125)
tortuman.right(90)
tortuman.fd(20)
tortuman.backward(40)
tortuman.penup()
tortuman.right(180)
tortuman.fd(70)
tortuman.left(90)
tortuman.fd(125)
tortuman.right(90)
tortuman.pendown()
#letra C
tortuman.left(90)
tortuman.left(90)
tortuman.circle(63, 180)
tortuman.penup()
tortuman.fd(20)
#tortuman.left(90)
tortuman.pendown()
#letra A
tortuman.left(70)
tortuman.fd(130)
tortuman.right(140)
tortuman.fd(130)
tortuman.backward(55)
tortuman.right(110)
tortuman.fd(50)
tortuman.penup()
tortuman.backward(180)
tortuman.forward(80)
tortuman.left(90)
tortuman.forward(70)
tortuman.backward(10)
tortuman.left(90)
tortuman.pendown()
#letra R
tortuman.lt(90)
tortuman.fd(130)
tortuman.bk(90)
tortuman.right(90)
tortuman.circle(50, 180)
tortuman.left(90)
tortuman.fd(100)
tortuman.left(45)
tortuman.fd(50)
tortuman.penup()
tortuman.left(90)
tortuman.forward(160)
tortuman.left(45)
tortuman.forward(10)
tortuman.left(90)
tortuman.forward(50)
tortuman.left(90)
tortuman.pendown()
#letra D
tortuman.forward(130)
tortuman.left(90)
tortuman.circle(65,180)
tortuman.penup()
tortuman.backward(150)
tortuman.pendown()
#letra O 
tortuman.circle(60)
#otros
tortuman.penup()
tortuman.forward(750)
tortuman.left(90)
tortuman.forward(160)
tortuman.left(90)
tortuman.pendown()
def curve():  
    for i in range(200):  
        tortuman.right(1)  
        tortuman.forward(1)  
tortuman. speed(10)  
tortuman.color("red", "pink")  
tortuman.begin_fill()  
tortuman.left(140)  
tortuman.forward(111.65)  
curve()  
tortuman.left(120)  
curve()  
tortuman.forward(111.65)  
tortuman.end_fill()  
tortuman.hideturtle()  
turtle.mainloop(90)
turtle.bye()

